"""Initial

Revision ID: 1e6c6546637d
Revises: dbf09b93a7ae
Create Date: 2024-01-08 12:19:27.668431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e6c6546637d'
down_revision: Union[str, None] = 'dbf09b93a7ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE members SET memberName = UPPER(memberName);")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE members SET memberName = LOWER(memberName);")
    # ### end Alembic commands ###
